sudo: false
language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
  
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "4"
    - node_js: "0.10"
    - node_js: "0.12"

notifications:
  email:
    on_success: never
    on_failure: never

before_script:
  - npm install standard
  - standard

script:
  - npm install istanbul
  - node --harmony node_modules/.bin/istanbul cover test.js

after_success:
  - npm install coveralls
  - cat coverage/lcov.info | coveralls
